project:
  type: default

# Allows for using the same LaTeX macros in HTML and PDF output
filters:
  - notebooks/_macros.lua

format:
  html:
    embed-resources: true
  pdf:
    include-in-header: notebooks/_macros.tex

# necessary to import demo from Quarto
#jupyter: markets-as-interference
#execute:
#  daemon: false