[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "demo"
version = "0.1.0"

[tool.setuptools]
packages = ["demo", "demo.mvp", "demo.figures"]
package-dir = {"demo" = "."}